// Generated by CoffeeScript 1.6.3
(function() {
  var Spooky, expect, initialize, should;

  Spooky = require('spooky');

  should = require('chai').should();

  expect = require('chai').expect;

  initialize = function(done) {
    var spooky;
    spooky = new Spooky({
      child: {
        transport: 'http'
      },
      casper: {
        logLevel: 'debug',
        verbose: true
      }
    }, function(err) {
      var e;
      if (err) {
        e = new Error('Failed to initialize SpookyJS');
        e.details = err;
        throw e;
      }
      spooky.debug = true;
      spooky.fails = [];
      return done();
    });
    spooky.on('error', function(e, stack) {
      console.error(e);
      if (stack) {
        return console.log(stack);
      }
    });
    spooky.on('console', function(line) {
      console.log(line);
      if (line.match(/FAIL/)) {
        return spooky.fails.push(line);
      }
    });
    spooky.on('hello', function(greeting) {
      return console.log(greeting);
    });
    return spooky.on('log', function(log) {
      if (log.space === 'remote') {
        return console.log(log.message.replace(/\- .*/, ''));
      }
    });
  };

  describe('Frontend tests', function() {
    var fails, ok, spooky;
    spooky = null;
    fails = [];
    ok = true;
    before(function(done) {
      return spooky = initialize(done);
    });
    after(function() {
      spooky.removeAllListeners();
      return spooky.destroy();
    });
    afterEach(function() {
      if (!ok) {
        return this.test.error(new Error(fails));
      }
    });
    it('Hello', function(done) {
      spooky.start('http://en.wikipedia.org/wiki/Spooky_the_Tuff_Little_Ghost');
      spooky.then(function() {
        this.emit('hello', 'Hello, from ' + this.evaluate(function() {
          return document.title;
        }));
        this.test.assertHttpStatus(199, 'successfully received 200 OK');
        return this.test.assertHttpStatus(200, 'successfully received 200 OK');
      });
      spooky.on('run.complete', function() {
        if (spooky.fails.length > 0) {
          console.log(this.test);
          fails.push(spooky.fails);
          ok = false;
        }
        return done();
      });
      return spooky.run(function() {
        return this.test.done();
      });
    });
    return it('Hello2', function(done) {
      spooky.start('http://en.wikipedia.org/wiki/Spooky_the_Tuff_Little_Ghost');
      spooky.then(function() {
        this.emit('hello', 'Hello, from ' + this.evaluate(function() {
          return document.title;
        }));
        this.test.assertHttpStatus(199, 'successfully received 200 OK');
        return this.test.assertHttpStatus(200, 'successfully received 200 OK');
      });
      spooky.on('run.complete', function() {
        if (spooky.fails.length > 0) {
          console.log(this.test);
          fails.push(spooky.fails);
          ok = false;
        }
        return done();
      });
      return spooky.run(function() {
        return this.test.done();
      });
    });
  });

}).call(this);
