// Generated by CoffeeScript 1.6.2
(function() {
  var start;

  start = function(app) {
    return app.get('/', function(req, res) {
      console.log("hello, world!");
      return res.render('index.ejs', {
        locals: {
          message: "Hello, world!"
        }
      });
    });
  };

  exports.start = start;

}).call(this);
