// Generated by CoffeeScript 1.6.3
(function() {
  (function(define) {
    return define([], function() {
      var buy, calcCPC, calcCPS, canBuy, earn, earnByClick, gainEquip, newPlayer, sell;
      if (typeof module !== "undefined" && module !== null) {
        this['_'] = require('underscore');
        this['Bakery'] = require('./bakery');
      }
      newPlayer = function(id, name) {
        return {
          id: id,
          name: name != null ? name : 'JoeJack',
          bakeries: Bakery.newBakeries,
          totalCookie: 0,
          equips: {}
        };
      };
      calcCPS = function(bakeries, equips) {
        return _.reduce(bakeries, function(r, amount, bakery) {
          return r + Bakery.calcCPS(bakery, amount, equips);
        }, 0);
      };
      calcCPC = function(bakeries, equips) {
        return 1;
      };
      canBuy = function(player, bakery) {
        return player.totalCookie >= Bakery.priceOf(bakery);
      };
      buy = function(player, bakery) {
        var price;
        if (canBuy(player, bakery)) {
          price = Bakery.priceOf(bakery);
          player.totalCookie -= price;
          player.bakeries[bakery] += 1;
          return price;
        } else {
          return null;
        }
      };
      sell = function(player, bakery) {
        if (player.bakeries[bakery] > 0) {
          player.totalCookie += Bakery.priceOf(bakery);
          return player.bakeries[bakery] -= 1;
        }
      };
      gainEquip = function(player, equip) {
        return player.equips[equip] = true;
      };
      earn = function(player, elapsedSec) {
        return player.totalCookie += calcCPS(player.bakeries, player.equips) * elapsedSec;
      };
      earnByClick = function(player) {
        return player.totalCookie += calcCPC(player.bakeries, player.equips);
      };
      return {
        newPlayer: newPlayer,
        calcCPS: calcCPS,
        calcCPC: calcCPC,
        canBuy: canBuy,
        buy: buy,
        gainEquip: gainEquip,
        earn: earn,
        earnByClick: earnByClick
      };
    });
  })(typeof define !== "undefined" && define !== null ? define : typeof module !== "undefined" && module !== null ? function(deps, factory) {
    return module.exports = factory();
  } : function(deps, factory) {
    return this['Player'] = factory();
  });

}).call(this);
