((define) ->
  define([], ->

    newEquips =
      'ReinforcedIndexFinger'                         : false
      'CarpalTunnelPreventionCream'                   : false
      'Ambidextrous'                                  : false
      'ThousandFingers'                               : false
      'MillionFingers'                                : false
      'BillionFingers'                                : false
      'TrillionFingers'                               : false
      'QuadrillionFingers'                            : false
      'QuintillionFingers'                            : false
      'SextillionFingers'                             : false
      'ForwardsFromGrandma'                           : false
      'SteelPlatedRollingPins'                        : false
      'LubricatedDentures'                            : false
      'PruneJuice'                                    : false
      'DoubleThickGlasses'                            : false
      'FarmerGrandmas'                                : false
      'WorkerGrandmas'                                : false
      'MinerGrandmas'                                 : false
      'CosmicGrandmas'                                : false
      'TransmutedGrandmas'                            : false
      'AlteredGrandmas'                               : false
      'GrandmasGrandmas'                              : false
      'Antigrandmas'                                  : false
      'CheapHoes'                                     : false
      'Fertilizer'                                    : false
      'CookieTrees'                                   : false
      'GeneticallyModifiedCookies'                    : false
      'GingerbreadScareclows'                         : false
      'SturdierConveyorBelts'                         : false
      'ChildLabor'                                    : false
      'Sweatshop'                                     : false
      'RadiumReactors'                                : false
      'Recombobulators'                               : false
      'SugarGas'                                      : false
      'Megadrill'                                     : false
      'Ultradrill'                                    : false
      'Ultimadrill'                                   : false
      'HBombMining'                                   : false
      'VanillaNebulae'                                : false
      'Wormholes'                                     : false
      'FrequentFlyer'                                 : false
      'WarpDrive'                                     : false
      'ChocolateMonoliths'                            : false
      'Antimony'                                      : false
      'EssenceOfDough'                                : false
      'TrueChocolate'                                 : false
      'Ambrosia'                                      : false
      'AquaCrustulae'                                 : false
      'AncientTablet'                                 : false
      'InsaneOatlingWorkers'                          : false
      'SoulBond'                                      : false
      'SanityDance'                                   : false
      'BraneTransplant'                               : false
      'FluxCapacitors'                                : false
      'TimeParadoxResolver'                           : false
      'QuantumConundrum'                              : false
      'CausalityEnforcer'                             : false
      'YestermorrowComparators'                       : false
      'SugarBosons'                                   : false
      'StringTheory'                                  : false
      'LargeMacaronCollider'                          : false
      'BigBangBake'                                   : false
      'ReverseCyclotrons'                             : false
      'OatmealRaisinCookies'                          : false
      'PeanutButterCookies'                           : false
      'PlainCookies'                                  : false
      'SugarCookies'                                  : false
      'CoconutCookies'                                : false
      'WhiteChocolateCookies'                         : false
      'MacadamiaNutCookies'                           : false
      'DoubleChipCookies'                             : false
      'WhiteChocolateMacadamiaNutCookies'             : false
      'AllChocolateCookies'                           : false
      'DarkChocolateCoatedCookies'                    : false
      'WhiteChocolateCoatedCookies'                   : false
      'EclipseCookies'                                : false
      'ZebraCookies'                                  : false
      'Snickerdoodles'                                : false
      'Stroopwafels'                                  : false
      'Macaroons'                                     : false
      'EmpireBiscuits'                                : false
      'BritishTeaBiscuits'                            : false
      'ChocolateBritishTeaBiscuits'                   : false
      'RoundBritishTeaBiscuits'                       : false
      'RoundChocolateBritishTeaBiscuits'              : false
      'RoundBritishTeaBiscuitsWithHeartMotif'         : false
      'RoundChocolateBritishTeaBiscuitsWithHeartMotif': false
      'Madeleines'                                    : false
      'Palets'                                        : false
      'Palmiers'                                      : false
      'Sables'                                        : false
      'Caramoas'                                      : false
      'Sagalongs'                                     : false
      'Shortfoils'                                    : false
      'WinMints'                                      : false
      'KittenHelpers'                                 : false
      'KittenWorkers'                                 : false
      'KittenEngineers'                               : false
      'KittenOverseers'                               : false
      'BingocenterResearchFacility'                   : false
      'SpecializedChocolateChips'                     : false
      'DesignerCocoaBeans'                            : false
      'RitualRollingPins'                             : false
      'UnderworldOvens'                               : false
      'OneMind'                                       : false
      'ExoticNuts'                                    : false
      'CommunalBrainsweep'                            : false
      'ArcaneSugar'                                   : false
      'ElderPact'                                     : false
      'ElderPledge'                                   : false
      'SacrificialRollingPins'                        : false
      'ElderCovenant'                                 : false
      'RevokeElderCovenant'                           : false
      'PlasticMouse'                                  : false
      'IronMouse'                                     : false
      'TitaniumMouse'                                 : false
      'AdamantiumMouse'                               : false
      'UnobtainiumMouse'                              : false
      'LuckyDay'                                      : false
      'Serendipity'                                   : false
      'GetLucky'                                      : false

    {
      newEquips: newEquips
    }
  )
)(define ? if module? then (deps, factory) -> module.exports = factory() else (deps, factory) -> @['Equip'] = factory())
